import Footer from "@/components/common/Footer";
import Header from "@/components/common/Header";
import "./globals.css";

export const metadata = {
  title: "Coffee Bean",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body
        style={{
          overflow: "auto !important",
          paddingRight: "0 !important",
          marginRight: "0 !important",
        }}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
