import Header from "@/components/dashboard/Header";
import Sidebar from "@/components/dashboard/Sidebar";
import "../dashboard.css";

export const metadata = {
  title: "Coffee Bean",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body
        className="inter_font bg-[#F9FAFB]"
        style={{
          overflow: "auto !important",
          paddingRight: "0 !important",
          marginRight: "0 !important",
        }}
      >
        <div className="flex items-start ">
          <Sidebar />
          <div className="w-full">
            <Header />{" "}
            <div className="p-8 overflow-auto custom_height bg-[#F9FAFB]">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
